# .github/workflows/frontend-ci.yml
name: Front-End CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # or 20/18, match your package.json engines

      - name: Install dependencies
        run: npm ci
        env:
          # prevent Next from trying to run analytics stuff
          NEXT_TELEMETRY_DISABLED: "1"

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
